SOUND_TOTAL_TIME = 5
FRAMES_PER_BUFFER = 1024
CHANNELS = 1
RATE = 44100
RECORD_SECONDS = 5
FILE_FOR_TESTING_PURPOSES_PATH = "D:\Person\VoiceTrainingTool\Tests\Resources\demo.wav"
READING_SIZE = 8*1024