DATA_DIR = '..\DATA'
USERS_DIR = '..\DATA\USERS'
TRAININGS_DIR = '..\DATA\USERS\{}\TRAININGS'
LTAS_FILE = '..\DATA\USERS\{}\TRAININGS\{}\ltas.txt'
SPECTRUM_FILE = '..\DATA\USERS\{}\TRAININGS\{}\spectrum.txt'
SOUND_FILE = '..\DATA\USERS\{}\TRAININGS\{}\sound.wav'
TRAINING_INFO_FILE = '..\DATA\USERS\{}\TRAININGS\{}\info.txt'
READINGS_DIR = '..\DATA\READINGS'
READING_FILE = '..\DATA\READINGS\{}'
USER_FILE = '..\DATA\USERS\{}'









